name: CI/CD pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: Build
        run: echo "building..."
      - name: Test
        run: echo "Testing..."
      - name: Deploy
        run: echo "Deploying..."
