name: CI/CD pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
        with:
          repository: manasahj97/simple-java-maven-app
          ref: main  
          fetch-depth: 0  
          submodules: true
      - name: Build
        run: echo "building..."
